### ISSUE TITLE
Allow for chain identifiers different from A

### ISSUE THREAD

**Issue by JoanaMPereira** [JudeWells/chainsaw#34]
Hi!

I have been using chainsaw to process some AFDB and ESM models, where the chain is always 'A'. But i wanted to use it over some chains extracted from PDB structures, where the chain may not be 'A'. However, it seems chainsaw does not work in these cases because it always expects that the chain identifier is 'A'. It may be worth to change this behaviour...

Best wishes
Joana

**Comment by JudeWells** [comment]
Hi Joana
Thanks for raising this issue,

There is a command line flag '--use_first_chain' which changes the default behaviour so that it will make predictions for whichever chain appears first in the pdb file.

eg:
python get_predictions.py --structure_file /path/to/file.pdb --use_first_chain

I think we will change it to make this the default behaviour in the next update.
let me know if this does / does not solve your problem.

**Comment by JudeWells** [comment]
Default behaviour is now to make predictions on the first chain that occurs in the PDB file
